env:
  browser: true
  node: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  no-unused-vars:
    - 0

