# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: Node

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '16.17.1'
      checkLatest: true

  - task: CmdLine@2
    displayName: Add Heroku remote address
    inputs:
      script: 'git remote add heroku https://23845d7b-06c7-487b-ad2d-f1602861cc7e@git.heroku.com/ancient-hollows-68245.git'
  
  - task: CmdLine@2
    displayName: LS
    inputs:
      script: 'ls'

  - task: CmdLine@2
    displayName: Download dependencies
    inputs:
      script: 'npm install'

  - task: CmdLine@2
    displayName: Show remote
    inputs:
      script: 'git remote show heroku'

  - task: CmdLine@2
    displayName: Push to heroku
    inputs:
      script: 'git push heroku master'


