# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    displayName: Add Heroku remote address
    inputs:
      script: 'git remote add heroku https://git.heroku.com/ancient-hollows-68245.git'

